### ISSUE TITLE
firehol analyzer error

### ISSUE THREAD

**Issue by garanews** [BSI-CERT-Bund/cortex-analyzers#6]
Hello,
I'm trying the firehol analyzer leaving settings to default but I am getting this error:
"errorMessage": "Error: Invalid output\n/usr/bin/env: python3: No such file or directory\n"

Under firehol_blocklists.py I have 
self.path = self.getParam('config.blocklistpath', '/tmp/fireholblocklists')
So I'm wondering why is not a valid output..

**Comment by 3c7** [comment]
Hey @garanews,

have you cloned https://github.com/firehol/blocklist-ipsets to /tmp/fireholblocklists?

**Comment by garanews** [comment]
I tried to do as you suggested but error persist, it seems I have another issue: python3
I am still running 2.7
There is any function where v3 is mandatory?

**Comment by 3c7** [comment]
I did not ensure compatibility for both python version and used new type annotations not available in python 2.

Please wait a little bit, currently we're migrating all analyzers to the main repository https://github.com/CERT-BDF/Cortex-Analyzers (see https://github.com/CERT-BDF/Cortex-Analyzers/pull/41). The main cortex-analyzer repository is python version independent.

**Comment by garanews** [comment]
That's fine, I will wait the main repository.
I have another question: are you going to create an analyzer for Cuckoo Sandbox? 
I'm using the https://github.com/spender-sandbox/cuckoo-modified and I am trying to modify the JoeSandbox analyzer but maybe you have already something ready :)

**Comment by 3c7** [comment]
Hey @garanews,
unfortunately I don't have a test environent for the cuckoo sandbox, so I'm not able to create an analyzer for that - sorry.

**Comment by 3c7** [comment]
Are you currently working on an analyzer regarding cuckoo sandbock? I'm currently setting up a cuckoo sandbox and will check if an analyzer can be implemented relatively easy.

**Comment by 3c7** [comment]
Closing this. Analyzers in the main repo (CERT-BDF/Cortex-Analyzers) will be python 2.7 and 3.5 compatible. Some of them are already published, the others will follow. :)
